Работа по заданию 7 спринта.
Zuhra2712/java-kanban pull request #2
Opened 2024-05-28 02:48 UTC by Zuhra2712

Пробую запустить в main. Не пропускает метод save(). Помоги разобраться. Направь меня,пожалуйста.

2024-05-28 19:14 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-05-28 19:14 UTC, LexLippi commented on resourses/task2.csv
> +
Пустые файлы не стоит коммитить

2024-05-28 19:14 UTC, LexLippi commented on src/model/Epic.java
> +        return subtasks;
А зачем так?

Это нарушает инкапсуляцию, если возвращать не копию коллекции. Должна быть веская причина так делать. Я пока ее не вижу

2024-05-28 19:14 UTC, LexLippi commented on src/model/Task.java
> +    public Integer getEpicId() {
Зачем этот метод в классе `Task`?

2024-05-28 19:14 UTC, LexLippi commented on src/service/FileBackedTaskManager.java
> +    public final File file;
Это явно не должно быть публичное поле

2024-05-28 19:14 UTC, LexLippi commented on src/service/FileBackedTaskManager.java
> +    private final String header = "id,type,name,status,description,epic"; // Заголовок таблицы
Для заголовка можно добавить модификатор `static`, так как это константа.
И использовать нейминг для констант:

https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2024-05-28 19:14 UTC, LexLippi commented on src/service/FileBackedTaskManager.java
> +    public FileBackedTaskManager(HistoryManager historyManager1, File file) {
Почему `historyManager1`?
Можно просто `historyManager`

2024-05-28 19:14 UTC, LexLippi commented on src/service/FileBackedTaskManager.java
> +    private String toString(Task task) {
Это лучше в класс `Task`  унести

2024-05-28 19:14 UTC, LexLippi commented on src/service/FileBackedTaskManager.java
> +    private static Task taskFromString(String value) {
Аналогично тому, что выше написал

2024-05-28 19:14 UTC, LexLippi commented on src/service/FileBackedTaskManager.java
> +        Task task = null;
Зачем заводить такую переменную?
Можно в каждой ветке `switch` сделать `return` и сэкономить на `break`

2024-05-28 19:14 UTC, LexLippi commented on src/service/FileBackedTaskManager.java
> +    }
Здесь может возникнуть проблема.

Пусть в истории 2 элемента с идентификаторами 1, 2.

Метод получения строки из истории выдаст строку `1,2,`
Когда мы эту строку разобьем по запятым, то получим три элемента `"1", "2", ""`. При попытке взять `Integer.valueOf` от последнего возникнет исключение. 

Этого надо избежать

2024-05-28 19:14 UTC, LexLippi commented on src/service/FileBackedTaskManager.java
> +        //     save();
Почему метод `save` закомментирован?
Внутреннее состояние истории изменится, поэтому необходимо его сохранить

2024-05-28 19:14 UTC, LexLippi commented on src/service/FileBackedTaskManager.java
> +        //save();
Метод `save` не должен быть закомментирован

2024-05-28 19:14 UTC, LexLippi commented on src/service/FileBackedTaskManager.java
> +    }
Если этот метод необходим только для тестирования, то лучше вынести его в отдельный класс

2024-05-28 19:14 UTC, LexLippi commented on src/service/FileBackedTaskManager.java
> +        Integer taskId = id;
Зачем нужна эта неиспользуемая переменная?

2024-05-28 19:14 UTC, LexLippi commented on src/service/FileBackedTaskManager.java
> +        TaskType taskType = task.getType();
Я бы советовал делать просто `switch(task.getType())`

2024-05-28 19:14 UTC, LexLippi commented on src/service/FileBackedTaskManager.java
> +                }
Можно использовать класс `Math` из пакета `java.lang`, а именно метод `max`

2024-05-28 19:14 UTC, LexLippi commented on src/service/InMemoryTaskManager.java
> +        return subtask;*/
Кажется, что закомментированный код нам необходим

2024-05-28 19:14 UTC, LexLippi commented on src/service/InMemoryTaskManager.java
> +    }
Эти методы должны быть задекларированы в интерфейсе

2024-05-29 02:51 UTC, Zuhra2712 commented on resourses/task2.csv
> +
Хорошо)

2024-05-29 02:57 UTC, Zuhra2712 commented on src/model/Task.java
> +    public Integer getEpicId() {
Оставила его в классе Subtask.

2024-05-29 03:40 UTC, Zuhra2712 commented on src/service/FileBackedTaskManager.java
> +    }
Сократила длину на 2 элемента. Пробел и запятая.
Можно было просто trim()? или он удалил бы только пробел и потом код упал бы из за того, что не получил бы значение после запятой ?

2024-05-31 05:15 UTC, Zuhra2712 commented on src/service/InMemoryTaskManager.java
> +        return subtask;*/
У меня этот код никак не проходит (((
Кручу верчу тут и никак

2024-05-31 05:22 UTC, Zuhra2712 commented on src/service/FileBackedTaskManager.java
> +        //save();
Он у меня не проходит

2024-06-03 08:31 UTC, LexLippi requested changes
Привет!

Отписался в чем ошибка при сохранении, надо поправить!

Желаю удачи!

2024-06-03 08:31 UTC, LexLippi commented on src/service/ClassForTesting.java
> +}
Файлы используемые для тестирования лучше не коммитить в итоговый репозиторий

2024-06-03 08:31 UTC, LexLippi commented on src/service/FileBackedTaskManager.java
> +                bufferedWriter.write(entry.getValue().toString());
Вот тут неправильную инфу записываешь.

Вызываешь метод `.toString()`, который в классе `Task` находится в строчках 85-92, надо либо правильно его определить, либо передавать в метод `toString` значение `entry.getValue()`,  чтобы вызывался метод, который мы ожидаем увидеть из строчек 59-61.

Аналогично для других типов задач

2024-06-03 08:31 UTC, LexLippi commented on src/service/TaskManager.java
> +    }
Это зачем?

2024-06-03 09:26 UTC, Zuhra2712 commented on src/service/ClassForTesting.java
> +}
Поняла)

2024-06-04 07:38 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-06-05 04:30 UTC, merged